/** SF Symbol name (without the `sf:` prefix) → MaterialCommunityIcons name.
 * Android-only; iOS renders SF Symbols natively via expo-image. */
export const SF_TO_MATERIAL: Record<string, string> = {
  'archivebox': 'archive-outline',
  'archivebox.fill': 'archive',
  'arrow.down.circle': 'arrow-down-circle-outline',
  'arrow.up': 'arrow-up',
  'books.vertical': 'bookshelf',
  'brain': 'brain',
  'bubble.left.and.bubble.right': 'forum-outline',
  'calendar.badge.plus': 'calendar-plus',
  'camera.fill': 'camera',
  'checkmark': 'check',
  'checkmark.circle.fill': 'check-circle',
  'checkmark.seal.fill': 'check-decagram',
  'chevron.down': 'chevron-down',
  'chevron.right': 'chevron-right',
  'chevron.up': 'chevron-up',
  'clock.arrow.2.circlepath': 'autorenew',
  'clock.arrow.circlepath': 'history',
  'cpu': 'chip',
  'doc.text': 'file-document-outline',
  'exclamationmark.shield.fill': 'shield-alert',
  'gearshape': 'cog-outline',
  'hammer.fill': 'hammer',
  'key': 'key-variant',
  'line.3.horizontal': 'menu',
  'magnifyingglass': 'magnify',
  'pencil': 'pencil',
  'person.crop.circle': 'account-circle-outline',
  'photo.on.rectangle': 'image-multiple-outline',
  'pin.fill': 'pin',
  'pin.slash.fill': 'pin-off',
  'play.circle.fill': 'play-circle',
  'plus': 'plus',
  'qrcode.viewfinder': 'qrcode-scan',
  'questionmark.circle': 'help-circle-outline',
  'questionmark.folder': 'folder-question-outline',
  'slash.circle': 'cancel',
  'sparkles': 'creation',
  'square.and.arrow.up': 'export-variant',
  'square.and.pencil': 'square-edit-outline',
  'trash.fill': 'delete',
  'tray.and.arrow.up.fill': 'tray-arrow-up',
  'xmark': 'close',
  'xmark.circle.fill': 'close-circle',
};
